GET {{baseUrl}}/v1/products/1

### POST USER
POST {{baseUrl}}/v1/products
Accept: application/json
Content-Type: application/json

{
  "name": "Product 233",
  "price": 1000,
  "quantity": 10,
  "categoryId": 1
}

### GET ALL PRODUCT
GET {{baseUrl}}/v1/products

### PUT PRODUCT

PUT {{baseUrl}}/v1/products/2
Accept: application/json
Content-Type: application/json

{
  "name": "Product 2 edit",
  "price": 1000,
  "quantity": 10
}

### DELETE PRODUCT
DELETE {{baseUrl}}/v1/products/23333

### SOFT DELETE
DELETE {{baseUrl}}/v1/products/1/soft



### POST CATEGORY
POST {{baseUrl}}/v1/categories
Accept: application/json
Content-Type: application/json

{
  "categoryName": "mahal"
}

### GET ALL CATEGORY
GET {{baseUrl}}/v1/categories

### PUT CATEGORY
PUT {{baseUrl}}/v1/categories/1
Accept: application/json
Content-Type: application/json

{
  "categoryName": "barang ghoib"
}

### SOFT DELETE CATEGORY
DELETE {{baseUrl}}/v1/categories/1/soft

### DELETE CATEGORY
DELETE {{baseUrl}}/v1/categories/1

### POST GET FILE

POST {{baseUrl}}/v1/files