GET http://localhost:8000/v1/products/2

### POST USER
POST http://localhost:8000/v1/products
Accept: application/json
Content-Type: application/json

{
  "name": "Product 2",
  "price": 1000,
  "quantity": 10
}

### GET ALL PRODUCT
GET http://localhost:8000/v1/products

### PUT PRODUCT

PUT http://localhost:8000/v1/products/2
Accept: application/json
Content-Type: application/json

{
  "name": "Product 2 edit",
  "price": 1000,
  "quantity": 10
}


